repackage (#200)
* repackage

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -6,93 +6,43 @@
 # IMPORT GENERIC HELPERS
 #=================================================
 
+source _common.sh
 source /usr/share/yunohost/helpers
 
 #=================================================
 # MANAGE SCRIPT FAILURE
 #=================================================
 
+ynh_clean_setup () {
+  ynh_clean_check_starting
+}
 # Exit if an error occurs during the execution of the script
 ynh_abort_if_errors
 
 #=================================================
 # LOAD SETTINGS
 #=================================================
+ynh_script_progression --message="Loading installation settings..." --weight=2
 
 app=$YNH_APP_INSTANCE_NAME
-domain=$(ynh_app_setting_get $app domain)
-path_url=$(ynh_app_setting_get $app path) # used during nginx configuration
-is_public=$(ynh_app_setting_get $app is_public)
-port=$(ynh_app_setting_get $app port)
-mattermost_user="$app"
 
-root_path="$(pwd)/.."
-final_path="/var/www/$app"
-data_path="/home/yunohost.app/$app"
-logs_path="/var/log/$app"
+domain=$(ynh_app_setting_get --app=$app --key=domain)
+path_url=$(ynh_app_setting_get --app=$app --key=path)
+is_public=$(ynh_app_setting_get --app=$app --key=is_public)
+port=$(ynh_app_setting_get --app=$app --key=port)
+final_path=$(ynh_app_setting_get --app=$app --key=final_path)
+language=$(ynh_app_setting_get --app=$app --key=language)
+db_name=$(ynh_app_setting_get --app=$app --key=db_name)
 
 #=================================================
-# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+# CHECK VERSION
 #=================================================
+ynh_script_progression --message="Checking version..." --weight=1
 
-# Backup the current version of the app
-# (NB: `tee` uses process substitution rather than a pipe,
-# to avoid spawning a subshell that would not save global
-# variables defined by `ynh_backup_before_upgrade`.)
-ynh_backup_before_upgrade > >(tee "upgrade.log")
-# Ensure the backup can be restored
-if grep -q "mattermost: Warning$" "upgrade.log"; then
-  can_restore_backup=false
-else
-  can_restore_backup=true
-fi
-
-# If the upgrade fails…
-ynh_clean_setup () {
-  if [ "$can_restore_backup" = true ]; then
-    # Stop attempting to restart the app
-    if $(systemctl -q is-active "$app"); then
-      systemctl stop "$app"
-    fi
-    # Restore the backup
-    ynh_restore_upgradebackup
-
-  else
-    # Backup restoration is not available:
-    # let's try at least to restart the server.
-    systemctl start "$app"
-  fi
-}
-
-# Exit if an error occurs during the execution of the script
-ynh_abort_if_errors
+upgrade_type=$(ynh_check_app_version_changed)
 
 #=================================================
-# STOP SERVER
-#=================================================
-
-# Stop the server (if the app is already using systemd)
-if $(systemctl -q is-active "$app"); then
-  systemctl stop "$app"
-fi
-
-# Legacy, for previous versions of this app which used supervisor
-if [ -f "/etc/supervisor/conf.d/${app}.conf" ]; then
-  supervisorctl stop "$app"
-  rm -f "/etc/supervisor/conf.d/${app}.conf"
-fi
-
-#=================================================
-# BACKUP CONFIGURATION FILE
-#=================================================
-
-config_file="$final_path/config/config.json"
-backup_config_file="/tmp/config.json"
-
-cp -f "$config_file" "$backup_config_file"
-
-#=================================================
-# MIGRATE SETTINGS FROM PREVIOUS VERSIONS
+# ENSURE DOWNWARD COMPATIBILITY
 #=================================================
 
 # Convert is_public from "Yes"/"No" to 1 / 0
@@ -101,77 +51,180 @@ if [[ $is_public == "Yes" ]]; then
 elif [[ $is_public == "No" ]]; then
   is_public=0
 fi
-ynh_app_setting_set "$app" is_public "$is_public"
+ynh_app_setting_set --app=$app --key=is_public --value=$is_public
 
 # Save the port used if not present
 if ! [[ "$port" ]]; then
   port=8065
-  ynh_app_setting_set "$app" port "$port"
+  ynh_app_setting_set --app=$app --key=port --value=$port
 fi
+
+# # Language if not present
+# if ! [[ "$language" ]]; then
+#   language="en"
+#   ynh_app_setting_set --app=$app --key=language --value=$language
+# fi
+
+# # Cleaning legacy permissions
+# if ynh_legacy_permissions_exists; then
+#   ynh_legacy_permissions_delete_all
+
+#   ynh_app_setting_delete --app=$app --key=is_public
+# fi
+
+# if ! ynh_permission_exists --permission="admin"; then
+#   # Create the required permissions
+#   ynh_permission_create --permission="admin" --url="/admin" --allowed=$admin
+# fi
+
+# # Create a permission if needed
+# if ! ynh_permission_exists --permission="api"; then
+#   ynh_permission_create --permission="api" --url "/api" --allowed="visitors" --show_tile="false" --protected="true"
+# fi
+
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
+ynh_script_progression --message="Backing up the app before upgrading (may take a while)..." --weight=1
+
+# Backup the current version of the app
+ynh_backup_before_upgrade
+ynh_clean_setup () {
+  # Restore it if the upgrade fails
+  ynh_restore_upgradebackup
+}
+# Exit if an error occurs during the execution of the script
+ynh_abort_if_errors
+
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+# STOP SYSTEMD SERVICE
+#=================================================
+ynh_script_progression --message="Stopping a systemd service..." --weight=3
+
+ynh_systemd_action --service_name=$app --action=stop --log_path="/var/log/$app/$app.log"
 
 #=================================================
 # DOWNLOAD, CHECK AND UNPACK SOURCE
 #=================================================
 
-ynh_app_setting_set "$app" final_path "$final_path"
-ynh_setup_source "$final_path"
+if [ "$upgrade_type" == "UPGRADE_APP" ]
+then
+  ynh_script_progression --message="Upgrading source files..." --weight=2
 
-#=================================================
-# RESTORE CONFIGURATION FILE
-#=================================================
+  # Create a temporary directory
+  tmpdir="$(mktemp -d)"
 
-cp -f "$backup_config_file" "$config_file"
+  # Backup the config file in the temp dir
+  cp -a "$final_path/config/config.json" "$tmpdir/config.json"
+
+  # Remove the app directory securely
+  ynh_secure_remove --file="$final_path"
+
+  # Download, check integrity, uncompress and patch the source from app.src
+  ynh_setup_source --dest_dir="$final_path"
+
+  # Copy the admin saved settings from tmp directory to final path  
+  cp -a "$tmpdir/config.json" "$final_path/config/config.json" 
+
+  # Remove the tmp directory securely
+  ynh_secure_remove --file="$tmpdir"
+fi
 
 #=================================================
 # NGINX CONFIGURATION
 #=================================================
+ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=5
 
+# Create a dedicated NGINX config
 ynh_add_nginx_config
 
 #=================================================
-# SYSTEMD CONFIGURATION
+# CREATE DEDICATED USER
 #=================================================
+ynh_script_progression --message="Making sure dedicated system user exists..." --weight=1
 
+# Create a dedicated user (if not existing)
+ynh_system_user_create --username=$app
+
+#=================================================
+# SETUP SYSTEMD
+#=================================================
+ynh_script_progression --message="Upgrading systemd configuration..." --weight=2
+
+# Create a dedicated systemd config
 ynh_add_systemd_config
-
-#=================================================
-# ADVERTISE SERVICE IN ADMIN PANEL
-#=================================================
-
-yunohost service add "$app" --log "$logs_path/mattermost.log"
 
 #=================================================
 # SPECIFIC UPGRADE STEPS
 #=================================================
 
-# Fix log FileLocation path (changed in Mattermost 3.8, makes Mattermost >= 4.2 crash)
-# https://docs.mattermost.com/administration/changelog.html#release-v3-8-3
-ynh_replace_string --match_string "\"FileLocation\": \"/var/log/mattermost.log\"" --replace_string "\"FileLocation\": \"/var/log\"" --target_file "$config_file"
+# # Fix log FileLocation path (changed in Mattermost 3.8, makes Mattermost >= 4.2 crash)
+# # https://docs.mattermost.com/administration/changelog.html#release-v3-8-3
+# ynh_replace_string --match_string "\"FileLocation\": \"/var/log/mattermost.log\"" --replace_string "\"FileLocation\": \"/var/log\"" --target_file "$config_file"
 
-# Move log files to a directory (rather than directly in /var/log)
-# See https://github.com/YunoHost-Apps/mattermost_ynh/issues/61
-mkdir -p "$logs_path"
-ynh_replace_string --match_string "\"FileLocation\": \"/var/log\"" --replace_string "\"FileLocation\": \"$logs_path\"" --target_file "$config_file"
-if [ -f "/var/log/${app}.log" ]; then
-  mv "/var/log/${app}.log" "$logs_path/"
-fi
+# # Move log files to a directory (rather than directly in /var/log)
+# # See https://github.com/YunoHost-Apps/mattermost_ynh/issues/61
+# mkdir -p "$logs_path"
+# ynh_replace_string --match_string "\"FileLocation\": \"/var/log\"" --replace_string "\"FileLocation\": \"$logs_path\"" --target_file "$config_file"
+# if [ -f "/var/log/${app}.log" ]; then
+#   mv "/var/log/${app}.log" "$logs_path/"
+# fi
+
+#=================================================
+# CREATE DIRECTORY FOR DATA
+#=================================================
+ynh_script_progression --message="Creating the data directory..." --weight=1
+
+# Define app's data directory
+data_path="/home/yunohost.app/$app"
+# Create datadir folder
+mkdir -p $data_path
+# Give permission to the datadir
+chown -R $app: "$data_path"
 
 #=================================================
 # RESTORE FILE PERMISSIONS
 #=================================================
 
-chown -R "$mattermost_user:www-data" "$final_path"
-chown -R "$mattermost_user:www-data" "$data_path"
-chown -R "$mattermost_user:adm"      "$logs_path"
+chown -R $app: $final_path
+chmod -R g+w $final_path
+
+chown -R $app: "/var/log/$app"
+
+#=================================================
+# SETUP LOGROTATE
+#=================================================
+ynh_script_progression --message="Upgrading logrotate configuration..." --weight=1
+
+# Use logrotate to manage app-specific logfile(s)
+ynh_use_logrotate --non-append
+
+#=================================================
+# INTEGRATE SERVICE IN YUNOHOST
+#=================================================
+ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
+
+yunohost service add $app --description="Collaboration platform built for developers" --log="/var/log/$app/$app.log"
+
+#=================================================
+# START SYSTEMD SERVICE
+#=================================================
+ynh_script_progression --message="Starting a systemd service..." --weight=2
+
+# Start a systemd service
+ynh_systemd_action --service_name=$app --action=start --log_path="systemd" --line_match="Started Mattermost"
 
 #=================================================
 # RELOAD NGINX
 #=================================================
+ynh_script_progression --message="Reloading NGINX web server..." --weight=1
 
-service nginx reload
+ynh_systemd_action --service_name=nginx --action=reload
 
 #=================================================
-# START SERVER
+# END OF SCRIPT
 #=================================================
 
-systemctl start "$app"
+ynh_script_progression --message="Upgrade of $app completed" --last
